"""Inventory generation from real deployment outputs.

This component exists to enforce one honesty rule: **no address is ever invented**. The
Ansible project is generated before anything is deployed, so it cannot know where its
hosts will live. Only after ``terraform apply`` do real addresses exist, and only then
does this generator run.

A host whose address is missing from the outputs is emitted with the reason recorded, not
with a plausible-looking guess.
"""

from __future__ import annotations

from typing import Any

from src.application.ports.generation import DeploymentOutputs
from src.application.ports.generation import InventoryGenerator as InventoryGeneratorPort
from src.domain.cloud.configuration import ConfigurationHost
from src.domain.cloud.models import CloudArchitecture
from src.domain.generation.models import GeneratedFile
from src.infrastructure.generators.ansible.generator import INVENTORY_PLACEHOLDER_PATH
from src.infrastructure.generators.ansible.yaml_writer import dump_yaml
from src.shared.errors import DeploymentError

__all__ = ["TerraformOutputInventoryGenerator"]

GENERATOR_NAME = "TerraformOutputInventoryGenerator"

_HEADER = (
    "Generated by TopoForge-AI from deployment outputs. Do not edit by hand.",
    "Addresses below are the real addresses reported after apply.",
)


class TerraformOutputInventoryGenerator(InventoryGeneratorPort):
    """Builds ``inventory/hosts.yml`` from the addresses a deployment actually produced."""

    @property
    def name(self) -> str:
        return GENERATOR_NAME

    def generate(
        self, architecture: CloudArchitecture, outputs: DeploymentOutputs
    ) -> GeneratedFile:
        if outputs.is_empty:
            raise DeploymentError(
                "cannot build an inventory: the deployment reported no outputs. "
                "Inventory generation runs after a successful apply, never before."
            )

        configuration = architecture.configuration
        children: dict[str, Any] = {}
        unresolved: list[str] = []

        for group in configuration.groups():
            hosts: dict[str, Any] = {}
            for host in configuration.hosts_in_group(group):
                entry, resolved = self._host_entry(host, architecture, outputs)
                hosts[host.name] = entry
                if not resolved:
                    unresolved.append(host.name)
            children[group] = {"hosts": hosts}

        document: dict[str, Any] = {"all": {"children": children}}
        if configuration.global_variables:
            document["all"]["vars"] = dict(configuration.global_variables)

        header = list(_HEADER)
        if outputs.deployment_id:
            header.append(f"Deployment: {outputs.deployment_id}")
        if unresolved:
            # Recorded in the file itself, so an operator reading the inventory sees the
            # gap rather than discovering it as a connection timeout.
            header.extend(
                [
                    "",
                    "The deployment reported no address for these hosts; they are marked",
                    "unreachable rather than given a guessed address:",
                    *(f"  - {name}" for name in unresolved),
                ]
            )

        return GeneratedFile(
            path=INVENTORY_PLACEHOLDER_PATH,
            content=dump_yaml(document, header=tuple(header)),
            language="yaml",
        )

    # ------------------------------------------------------------------ #
    def _host_entry(
        self,
        host: ConfigurationHost,
        architecture: CloudArchitecture,
        outputs: DeploymentOutputs,
    ) -> tuple[dict[str, Any], bool]:
        address = outputs.address_for(host.compute_id)
        private = outputs.compute_private_addresses.get(host.compute_id)

        # An explicit output reference on the host wins: the cloud translation knew which
        # output would carry this address.
        if address is None and host.address_output_ref:
            candidate = outputs.values.get(host.address_output_ref)
            address = str(candidate) if candidate is not None else None

        entry: dict[str, Any] = {
            "topoforge_compute_id": host.compute_id,
        }
        if address is not None:
            entry["ansible_host"] = address
        else:
            entry["topoforge_address_pending"] = True
            entry["topoforge_unreachable_reason"] = (
                "the deployment reported no address for this compute resource"
            )
        if private is not None and private != address:
            entry["topoforge_private_address"] = private

        entry["ansible_connection"] = host.connection.value
        if host.remote_user:
            entry["ansible_user"] = host.remote_user

        if host.requires_bastion:
            bastion_address = self._bastion_address(host, architecture, outputs)
            if bastion_address is not None:
                user = host.remote_user or "ec2-user"
                entry["ansible_ssh_common_args"] = (
                    f"-o ProxyCommand=\"ssh -W %h:%p -q {user}@{bastion_address}\""
                )
            else:
                entry["topoforge_bastion_pending"] = True

        entry.update(host.variables)
        return entry, address is not None

    @staticmethod
    def _bastion_address(
        host: ConfigurationHost, architecture: CloudArchitecture, outputs: DeploymentOutputs
    ) -> str | None:
        if host.bastion_host_id:
            bastion = next(
                (
                    candidate
                    for candidate in architecture.configuration.hosts
                    if candidate.id == host.bastion_host_id
                ),
                None,
            )
            if bastion is not None:
                return outputs.address_for(bastion.compute_id)

        # Otherwise use whichever compute resource the architecture marked as the bastion.
        for instance in architecture.infrastructure.compute:
            if instance.is_bastion:
                return outputs.address_for(instance.id)
        return None
