"""Deterministic Terraform generation.

``CloudArchitecture`` in, ``TerraformProject`` out. No LLM, no RAG, no network access, no
filesystem access, no clock in the output. Given the same architecture this produces
byte-identical files, which is what the golden tests assert.

Resource mapping decisions live in :mod:`.mappings.aws`, never here. This module's job is
ordering, file layout, variables, outputs and provider configuration.
"""

from __future__ import annotations

from typing import Any

from src.application.ports.generation import TerraformGenerator as TerraformGeneratorPort
from src.domain.cloud.models import CloudArchitecture
from src.domain.cloud.resources import CloudProvider
from src.domain.generation.models import (
    GeneratedFile,
    GeneratorWarning,
    ProjectKind,
    TerraformProject,
    WarningSeverity,
)
from src.infrastructure.generators.terraform.hcl import Block, HCLDocument, Raw
from src.infrastructure.generators.terraform.mappings.aws import (
    MappingContext,
    build_registry,
    terraform_identifier,
)
from src.shared.errors import UnsupportedInputError, ValidationError

__all__ = ["AWSTerraformGenerator"]

GENERATOR_NAME = "AWSTerraformGenerator"
GENERATOR_VERSION = "1.0.0"

_HEADER = (
    "Generated by TopoForge-AI. Do not edit by hand.",
    "Regenerate from cloud_architecture.json instead: edits here are overwritten.",
)

#: Resources are emitted in dependency order. Terraform resolves references itself, but a
#: stable, readable order makes generated code and its diffs reviewable by a human.
_EMISSION_ORDER: tuple[str, ...] = (
    "virtual_network",
    "subnet",
    "gateway",
    "route_table",
    "security_group",
    "compute",
    "database",
    "load_balancer",
)


class AWSTerraformGenerator(TerraformGeneratorPort):
    """Renders AWS Terraform from a cloud architecture."""

    def __init__(self, *, terraform_version: str = ">= 1.6", aws_provider_version: str = "~> 5.0"):
        self._terraform_version = terraform_version
        self._aws_provider_version = aws_provider_version

    @property
    def name(self) -> str:
        return GENERATOR_NAME

    @property
    def version(self) -> str:
        return GENERATOR_VERSION

    @property
    def kind(self) -> ProjectKind:
        return ProjectKind.TERRAFORM

    # ------------------------------------------------------------------ #
    def generate(self, architecture: CloudArchitecture) -> TerraformProject:
        self._reject_unsupported(architecture)

        context = MappingContext(architecture=architecture)
        self._index_addresses(architecture, context)

        registry = build_registry()
        resource_blocks: list[Block] = []

        for kind in _EMISSION_ORDER:
            mapper = registry[kind]
            for resource in self._resources_of_kind(architecture, kind):
                resource_blocks.extend(mapper(resource, context))

        if not resource_blocks:
            raise ValidationError(
                "the cloud architecture produced no Terraform resources; nothing could be "
                "mapped to AWS",
                issues=[warning.model_dump() for warning in context.warnings],
            )

        files = [
            self._providers_file(architecture),
            self._data_file(),
            self._main_file(resource_blocks),
            self._variables_file(architecture, context),
            self._outputs_file(context),
            self._tfvars_example(architecture, context),
            self._readme(architecture, context),
        ]

        return TerraformProject(
            files=tuple(files),
            warnings=tuple(context.warnings) + self._coverage_warnings(architecture),
            generator_name=self.name,
            generator_version=self.version,
            cloud_architecture_id=architecture.cloud_architecture_id,
            cloud_architecture_revision=architecture.metadata.revision,
            required_providers={"aws": self._aws_provider_version},
            required_variables=tuple(sorted(context.required_variables)),
            declared_outputs=tuple(sorted(context.outputs)),
            metadata={
                "region": architecture.region,
                "resource_count": str(len(resource_blocks)),
            },
        )

    # ------------------------------------------------------------------ #
    def _reject_unsupported(self, architecture: CloudArchitecture) -> None:
        if architecture.provider is not CloudProvider.AWS:
            raise UnsupportedInputError(
                f"{self.name} generates AWS only; this architecture targets "
                f"{architecture.provider.value!r}",
                provider=architecture.provider.value,
            )
        if not architecture.is_valid:
            raise ValidationError(
                "refusing to generate Terraform from a cloud architecture that failed "
                "validation",
                issues=list(architecture.validation.errors),
            )
        if architecture.infrastructure.is_empty:
            raise ValidationError("the cloud architecture contains no infrastructure")

    def _index_addresses(self, architecture: CloudArchitecture, ctx: MappingContext) -> None:
        """Pre-compute every resource's Terraform address so mappers can cross-reference.

        Done in one pass before emission, so a route table can reference a gateway that
        has not been rendered yet.
        """
        from src.domain.cloud.resources import Gateway

        type_by_kind = {
            "virtual_network": "aws_vpc",
            "subnet": "aws_subnet",
            "route_table": "aws_route_table",
            "security_group": "aws_security_group",
            "compute": "aws_instance",
            "database": "aws_db_instance",
            "load_balancer": "aws_lb",
        }
        gateway_types = {
            "internet": "aws_internet_gateway",
            "nat": "aws_nat_gateway",
            "transit": "aws_ec2_transit_gateway",
            "peering": "aws_vpc_peering_connection",
            "vpn": "aws_vpn_gateway",
            "virtual_private": "aws_vpn_gateway",
        }

        for resource in architecture.infrastructure.all_resources():
            if isinstance(resource, Gateway):
                terraform_type = gateway_types.get(resource.type.value)
            else:
                terraform_type = type_by_kind.get(resource.kind.value)
            if terraform_type is None:
                continue
            ctx.addresses[resource.id] = (terraform_type, terraform_identifier(resource.id))

    @staticmethod
    def _resources_of_kind(architecture: CloudArchitecture, kind: str) -> tuple[Any, ...]:
        infrastructure = architecture.infrastructure
        return {
            "virtual_network": infrastructure.networks,
            "subnet": infrastructure.subnets,
            "route_table": infrastructure.route_tables,
            "gateway": infrastructure.gateways,
            "security_group": infrastructure.security_groups,
            "compute": infrastructure.compute,
            "database": infrastructure.databases,
            "load_balancer": infrastructure.load_balancers,
        }[kind]

    # ------------------------------------------------------------------ #
    def _providers_file(self, architecture: CloudArchitecture) -> GeneratedFile:
        terraform_block = Block("terraform")
        terraform_block.set("required_version", self._terraform_version)
        required = Block("required_providers")
        required.set("aws", {"source": "hashicorp/aws", "version": self._aws_provider_version})
        terraform_block.add(required)

        provider = Block("provider", ("aws",))
        provider.set("region", Raw("var.aws_region"))
        default_tags = Block("default_tags")
        default_tags.set(
            "tags",
            {
                "ManagedBy": "topoforge",
                "TopoForgeCloudArchitecture": architecture.cloud_architecture_id,
            },
        )
        provider.add(default_tags)

        document = HCLDocument(header=_HEADER).add(terraform_block).add(provider)
        return GeneratedFile(path="providers.tf", content=document.render(), language="hcl")

    def _data_file(self) -> GeneratedFile:
        zones = Block("data", ("aws_availability_zones", "available"))
        zones.set("state", "available")

        ami = Block(
            "data",
            ("aws_ami", "amazon_linux"),
            comments=("Default image for instances whose image was not specified.",),
        )
        ami.set("most_recent", True)
        ami.set("owners", ["amazon"])
        name_filter = Block("filter")
        name_filter.set("name", "name")
        name_filter.set("values", ["al2023-ami-*-x86_64"])
        ami.add(name_filter)

        document = HCLDocument(header=_HEADER).add(zones).add(ami)
        return GeneratedFile(path="data.tf", content=document.render(), language="hcl")

    def _main_file(self, blocks: list[Block]) -> GeneratedFile:
        document = HCLDocument(header=_HEADER).extend(blocks)
        return GeneratedFile(path="main.tf", content=document.render(), language="hcl")

    def _variables_file(
        self, architecture: CloudArchitecture, ctx: MappingContext
    ) -> GeneratedFile:
        document = HCLDocument(header=_HEADER)

        region = Block("variable", ("aws_region",))
        region.set("type", Raw("string"))
        region.set("description", "AWS region to deploy into")
        region.set("default", architecture.region)
        document.add(region)

        for variable in sorted(ctx.required_variables):
            block = Block("variable", (variable,))
            block.set("type", Raw("string"))
            block.set("description", _variable_description(variable))
            if variable.endswith(("_password", "_secret")):
                # Marked sensitive so the value never appears in plan or apply output.
                block.set("sensitive", True)
            document.add(block)

        return GeneratedFile(path="variables.tf", content=document.render(), language="hcl")

    def _outputs_file(self, ctx: MappingContext) -> GeneratedFile:
        document = HCLDocument(header=_HEADER)
        for name in sorted(ctx.outputs):
            value, description = ctx.outputs[name]
            block = Block("output", (name,))
            block.set("value", value)
            block.set("description", description)
            document.add(block)
        if document.is_empty:
            return GeneratedFile(
                path="outputs.tf",
                content="# No outputs: this architecture declares no addressable resources.\n",
                language="hcl",
            )
        return GeneratedFile(path="outputs.tf", content=document.render(), language="hcl")

    def _tfvars_example(
        self, architecture: CloudArchitecture, ctx: MappingContext
    ) -> GeneratedFile:
        lines = [
            "# Copy to terraform.tfvars and fill in. Never commit real secrets.",
            "",
            f'aws_region = "{architecture.region}"',
        ]
        for variable in sorted(ctx.required_variables):
            placeholder = (
                "CHANGE_ME" if not variable.endswith("_password") else "CHANGE_ME_USE_A_SECRET"
            )
            lines.append(f'{variable} = "{placeholder}"')
        return GeneratedFile(
            path="terraform.tfvars.example", content="\n".join(lines) + "\n", language="hcl"
        )

    def _readme(self, architecture: CloudArchitecture, ctx: MappingContext) -> GeneratedFile:
        counts = architecture.infrastructure.counts()
        lines = [
            f"# Terraform for {architecture.metadata.name}",
            "",
            f"Generated by `{self.name}` v{self.version} from "
            f"`cloud_architecture.json` (`{architecture.cloud_architecture_id}`).",
            "",
            "This directory is **generated output**. Change the cloud architecture and",
            "regenerate; edits made here are lost on the next generation.",
            "",
            "## Resources",
            "",
        ]
        lines.extend(f"- {name}: {count}" for name, count in counts.items() if count)
        lines.extend(
            [
                "",
                "## Usage",
                "",
                "```bash",
                "terraform init",
                "terraform validate",
                "terraform plan -out=tfplan",
                "# apply only after the plan has been approved in TopoForge",
                "terraform apply tfplan",
                "```",
                "",
                "## Configuration",
                "",
                "This project provisions infrastructure only. Host configuration "
                "(packages, services, files) is handled by the generated Ansible project, "
                "which runs after apply using an inventory built from these outputs.",
            ]
        )
        if ctx.required_variables:
            lines.extend(
                [
                    "",
                    "## Required variables",
                    "",
                    *(f"- `{variable}`" for variable in sorted(ctx.required_variables)),
                ]
            )
        return GeneratedFile(path="README.md", content="\n".join(lines) + "\n", language="markdown")

    # ------------------------------------------------------------------ #
    @staticmethod
    def _coverage_warnings(architecture: CloudArchitecture) -> tuple[GeneratorWarning, ...]:
        """Surface what the translation itself flagged, so it reaches the Terraform view."""
        warnings: list[GeneratorWarning] = []
        if architecture.unmapped:
            warnings.append(
                GeneratorWarning(
                    code="unmapped_network_concepts",
                    message=(
                        "the cloud translation could not represent: "
                        + ", ".join(architecture.unmapped)
                    ),
                    severity=WarningSeverity.MEDIUM,
                )
            )
        return tuple(warnings)


def _variable_description(variable: str) -> str:
    if variable == "ssh_key_name":
        return "Name of an existing EC2 key pair used for instance access"
    if variable.endswith("_username"):
        return f"Master username for {variable.removesuffix('_username')}"
    if variable.endswith("_password"):
        return f"Master password for {variable.removesuffix('_password')}"
    return f"Value for {variable}"
