"""Deterministic Ansible generation.

``CloudArchitecture.configuration`` in, ``AnsibleProject`` out. No LLM, no RAG.

The one thing this generator deliberately does **not** produce is a real inventory. Host
addresses do not exist until Terraform has applied, so the generated inventory is a
placeholder that documents the groups and says plainly that it is incomplete.
:class:`~src.infrastructure.generators.inventory.generator.TerraformOutputInventoryGenerator`
fills it in afterwards from actual outputs.

Ownership boundary: this generator configures machines. It never creates, resizes or
networks one — that is Terraform's job and duplicating it would put two systems in charge
of the same thing.
"""

from __future__ import annotations

from typing import Any

from src.application.ports.generation import AnsibleGenerator as AnsibleGeneratorPort
from src.domain.cloud.configuration import ConfigFile, ConfigurationHost, SystemRole
from src.domain.cloud.models import CloudArchitecture
from src.domain.generation.models import (
    AnsibleProject,
    GeneratedFile,
    GeneratorWarning,
    ProjectKind,
    WarningSeverity,
)
from src.infrastructure.generators.ansible.yaml_writer import dump_yaml
from src.shared.errors import ValidationError

__all__ = ["DefaultAnsibleGenerator", "INVENTORY_PLACEHOLDER_PATH"]

GENERATOR_NAME = "DefaultAnsibleGenerator"
GENERATOR_VERSION = "1.0.0"

INVENTORY_PLACEHOLDER_PATH = "inventory/hosts.yml"

_HEADER = (
    "Generated by TopoForge-AI. Do not edit by hand.",
    "Regenerate from cloud_architecture.json instead: edits here are overwritten.",
)

#: Package manager module. ``package`` is used rather than a distribution-specific module
#: so the generated role works across the images this platform may provision.
_PACKAGE_MODULE = "ansible.builtin.package"
_SERVICE_MODULE = "ansible.builtin.service"
_COPY_MODULE = "ansible.builtin.copy"
_TEMPLATE_MODULE = "ansible.builtin.template"


class DefaultAnsibleGenerator(AnsibleGeneratorPort):
    """Renders roles, playbooks and variable files from configuration requirements."""

    @property
    def name(self) -> str:
        return GENERATOR_NAME

    @property
    def version(self) -> str:
        return GENERATOR_VERSION

    @property
    def kind(self) -> ProjectKind:
        return ProjectKind.ANSIBLE

    # ------------------------------------------------------------------ #
    def generate(self, architecture: CloudArchitecture) -> AnsibleProject:
        configuration = architecture.configuration
        if configuration.is_empty:
            raise ValidationError(
                "the cloud architecture declares no configuration; there is nothing for "
                "Ansible to do. Check requires_configuration_stage before generating."
            )
        if not architecture.is_valid:
            raise ValidationError(
                "refusing to generate Ansible from a cloud architecture that failed "
                "validation",
                issues=list(architecture.validation.errors),
            )

        warnings: list[GeneratorWarning] = []
        unresolved = configuration.unresolved_role_names()
        if unresolved:
            warnings.append(
                GeneratorWarning(
                    code="unresolved_roles",
                    message=(
                        "hosts reference roles that are not defined and were skipped: "
                        + ", ".join(unresolved)
                    ),
                    severity=WarningSeverity.HIGH,
                )
            )

        files: list[GeneratedFile] = [
            self._ansible_cfg(),
            self._site_playbook(architecture, warnings),
            self._inventory_placeholder(architecture),
            *self._group_vars(architecture),
            *self._role_files(architecture, warnings),
            self._readme(architecture),
        ]

        return AnsibleProject(
            files=tuple(files),
            warnings=tuple(warnings),
            generator_name=self.name,
            generator_version=self.version,
            cloud_architecture_id=architecture.cloud_architecture_id,
            cloud_architecture_revision=architecture.metadata.revision,
            playbook_path="site.yml",
            inventory_path=INVENTORY_PLACEHOLDER_PATH,
            # True until the inventory generator replaces the placeholder post-apply.
            inventory_pending=True,
            role_names=tuple(role.name for role in configuration.roles),
            group_names=configuration.groups(),
        )

    # ------------------------------------------------------------------ #
    def _ansible_cfg(self) -> GeneratedFile:
        content = "\n".join(
            [
                "# Generated by TopoForge-AI. Do not edit by hand.",
                "[defaults]",
                f"inventory = {INVENTORY_PLACEHOLDER_PATH}",
                "roles_path = roles",
                "host_key_checking = False",
                "stdout_callback = yaml",
                "retry_files_enabled = False",
                "",
                "[ssh_connection]",
                "pipelining = True",
                "",
            ]
        )
        return GeneratedFile(path="ansible.cfg", content=content, language="ini")

    def _site_playbook(
        self, architecture: CloudArchitecture, warnings: list[GeneratorWarning]
    ) -> GeneratedFile:
        configuration = architecture.configuration
        defined = {role.name for role in configuration.roles}
        plays: list[dict[str, Any]] = []

        for group in configuration.groups():
            hosts = configuration.hosts_in_group(group)
            roles = _ordered_roles(hosts, configuration.roles)
            applicable = [name for name in roles if name in defined]
            if not applicable:
                continue
            play: dict[str, Any] = {
                "name": f"Configure {group} hosts",
                "hosts": group,
                "become": True,
                "gather_facts": True,
                "roles": applicable,
            }
            plays.append(play)

        ungrouped = [host for host in configuration.hosts if not host.groups]
        if ungrouped:
            warnings.append(
                GeneratorWarning(
                    code="hosts_without_group",
                    message=(
                        "hosts belong to no inventory group and are not configured by "
                        "site.yml: " + ", ".join(host.name for host in ungrouped)
                    ),
                    severity=WarningSeverity.MEDIUM,
                    subject_ids=tuple(host.id for host in ungrouped),
                )
            )

        if not plays:
            plays = [
                {
                    "name": "No configuration was derivable from the cloud architecture",
                    "hosts": "localhost",
                    "gather_facts": False,
                    "tasks": [
                        {
                            "name": "Report that there is nothing to configure",
                            "ansible.builtin.debug": {
                                "msg": "No roles were resolved for any inventory group."
                            },
                        }
                    ],
                }
            ]

        return GeneratedFile(
            path="site.yml", content=dump_yaml(plays, header=_HEADER), language="yaml"
        )

    def _inventory_placeholder(self, architecture: CloudArchitecture) -> GeneratedFile:
        """Inventory structure with no addresses.

        Real addresses only exist after apply. Emitting a guessed address here would be a
        lie that fails at connection time; an empty group is honest and the UI explains it.
        """
        configuration = architecture.configuration
        children: dict[str, Any] = {}
        for group in configuration.groups():
            children[group] = {
                "hosts": {
                    host.name: {
                        "topoforge_compute_id": host.compute_id,
                        "topoforge_address_pending": True,
                    }
                    for host in configuration.hosts_in_group(group)
                }
            }

        header = (
            *_HEADER,
            "",
            "PLACEHOLDER INVENTORY: it has no addresses.",
            "Host addresses are only known after `terraform apply`. TopoForge replaces",
            "this file from the deployment outputs before any playbook runs.",
        )
        return GeneratedFile(
            path=INVENTORY_PLACEHOLDER_PATH,
            content=dump_yaml({"all": {"children": children}}, header=header),
            language="yaml",
        )

    def _group_vars(self, architecture: CloudArchitecture) -> list[GeneratedFile]:
        configuration = architecture.configuration
        files: list[GeneratedFile] = []

        if configuration.global_variables:
            files.append(
                GeneratedFile(
                    path="group_vars/all.yml",
                    content=dump_yaml(dict(configuration.global_variables), header=_HEADER),
                    language="yaml",
                )
            )

        for group in configuration.groups():
            variables = configuration.group_variables.get(group)
            if not variables:
                continue
            files.append(
                GeneratedFile(
                    path=f"group_vars/{group}.yml",
                    content=dump_yaml(dict(variables), header=_HEADER),
                    language="yaml",
                )
            )

        for host in configuration.hosts:
            if not host.variables:
                continue
            files.append(
                GeneratedFile(
                    path=f"host_vars/{host.name}.yml",
                    content=dump_yaml(dict(host.variables), header=_HEADER),
                    language="yaml",
                )
            )
        return files

    def _role_files(
        self, architecture: CloudArchitecture, warnings: list[GeneratorWarning]
    ) -> list[GeneratedFile]:
        files: list[GeneratedFile] = []
        for role in architecture.configuration.roles:
            files.extend(self._one_role(role, warnings))
        return files

    def _one_role(
        self, role: SystemRole, warnings: list[GeneratorWarning]
    ) -> list[GeneratedFile]:
        base = f"roles/{role.name}"
        tasks: list[dict[str, Any]] = []
        handlers: list[dict[str, Any]] = []

        if role.packages:
            tasks.append(
                {
                    "name": f"Install packages for {role.name}",
                    _PACKAGE_MODULE: {
                        "name": [
                            f"{package.name}={package.version}" if package.version
                            else package.name
                            for package in role.packages
                        ],
                        "state": _package_state(role),
                    },
                }
            )

        for config_file in role.files:
            tasks.append(self._file_task(role, config_file, warnings))

        for service in role.services:
            tasks.append(
                {
                    "name": f"Ensure {service.name} is {service.state.value}",
                    _SERVICE_MODULE: {
                        "name": service.name,
                        "state": service.state.value,
                        "enabled": service.enabled,
                    },
                }
            )
            handlers.append(
                {
                    "name": f"restart {service.name}",
                    _SERVICE_MODULE: {"name": service.name, "state": "restarted"},
                }
            )

        if not tasks:
            tasks.append(
                {
                    "name": f"Role {role.name} declares no actions",
                    "ansible.builtin.debug": {
                        "msg": f"{role.name} has no packages, files or services defined."
                    },
                }
            )
            warnings.append(
                GeneratorWarning(
                    code="empty_role",
                    message=f"role {role.name!r} declares nothing to do",
                    severity=WarningSeverity.LOW,
                    subject_ids=(role.id,),
                )
            )

        files = [
            GeneratedFile(
                path=f"{base}/tasks/main.yml",
                content=dump_yaml(tasks, header=_HEADER),
                language="yaml",
            ),
            GeneratedFile(
                path=f"{base}/meta/main.yml",
                content=dump_yaml(
                    {
                        "galaxy_info": {
                            "role_name": role.name,
                            "description": role.description or f"TopoForge role {role.name}",
                        },
                        "dependencies": list(role.requires),
                    },
                    header=_HEADER,
                ),
                language="yaml",
            ),
        ]
        if handlers:
            files.append(
                GeneratedFile(
                    path=f"{base}/handlers/main.yml",
                    content=dump_yaml(handlers, header=_HEADER),
                    language="yaml",
                )
            )
        if role.variables:
            files.append(
                GeneratedFile(
                    path=f"{base}/defaults/main.yml",
                    content=dump_yaml(dict(role.variables), header=_HEADER),
                    language="yaml",
                )
            )
        for config_file in role.files:
            if config_file.content is not None:
                files.append(
                    GeneratedFile(
                        path=f"{base}/files/{_asset_name(config_file.path)}",
                        content=config_file.content,
                    )
                )
        return files

    def _file_task(
        self, role: SystemRole, config_file: ConfigFile, warnings: list[GeneratorWarning]
    ) -> dict[str, Any]:
        arguments: dict[str, Any] = {"dest": config_file.path}
        if config_file.template:
            module = _TEMPLATE_MODULE
            arguments["src"] = config_file.template
        elif config_file.content is not None:
            module = _COPY_MODULE
            arguments["src"] = _asset_name(config_file.path)
        else:
            module = _COPY_MODULE
            arguments["content"] = ""
            warnings.append(
                GeneratorWarning(
                    code="file_without_source",
                    message=(
                        f"{role.name}: {config_file.path} declares neither content nor a "
                        "template; an empty file will be written"
                    ),
                    severity=WarningSeverity.MEDIUM,
                    subject_ids=(role.id,),
                )
            )
        for key, value in (
            ("owner", config_file.owner),
            ("group", config_file.group),
            ("mode", config_file.mode),
        ):
            if value:
                arguments[key] = value

        task: dict[str, Any] = {"name": f"Write {config_file.path}", module: arguments}
        if config_file.notifies:
            task["notify"] = [f"restart {service}" for service in config_file.notifies]
        return task

    def _readme(self, architecture: CloudArchitecture) -> GeneratedFile:
        configuration = architecture.configuration
        lines = [
            f"# Ansible for {architecture.metadata.name}",
            "",
            f"Generated by `{self.name}` v{self.version} from "
            f"`cloud_architecture.json` (`{architecture.cloud_architecture_id}`).",
            "",
            "This project **configures** hosts. It does not create them: provisioning is",
            "Terraform's responsibility, and nothing here duplicates it.",
            "",
            "## Inventory",
            "",
            f"`{INVENTORY_PLACEHOLDER_PATH}` is a **placeholder** and contains no addresses.",
            "Host addresses exist only after `terraform apply`; TopoForge regenerates the",
            "inventory from the deployment outputs before running any playbook.",
            "",
            "## Groups",
            "",
        ]
        lines.extend(
            f"- `{group}`: "
            + ", ".join(host.name for host in configuration.hosts_in_group(group))
            for group in configuration.groups()
        )
        lines.extend(["", "## Roles", ""])
        lines.extend(f"- `{role.name}`" for role in configuration.roles)
        lines.extend(
            [
                "",
                "## Usage",
                "",
                "```bash",
                "ansible-playbook site.yml --syntax-check",
                "ansible-playbook site.yml --check     # dry run against real hosts",
                "ansible-playbook site.yml",
                "```",
            ]
        )
        return GeneratedFile(path="README.md", content="\n".join(lines) + "\n", language="markdown")


def _ordered_roles(
    hosts: tuple[ConfigurationHost, ...], roles: tuple[SystemRole, ...]
) -> list[str]:
    """Role names for a group, dependency-ordered and deduplicated.

    Ordering is a stable topological sort over ``SystemRole.requires``: a role is emitted
    after everything it requires. Cycles are broken deterministically by declaration
    order rather than raising, so one bad dependency cannot block an entire generation.
    """
    wanted: list[str] = []
    for host in hosts:
        for name in host.roles:
            if name not in wanted:
                wanted.append(name)

    by_name = {role.name: role for role in roles}
    ordered: list[str] = []
    visiting: set[str] = set()

    def visit(name: str) -> None:
        if name in ordered or name in visiting:
            return
        visiting.add(name)
        role = by_name.get(name)
        if role is not None:
            for dependency in role.requires:
                visit(dependency)
        visiting.discard(name)
        if name not in ordered:
            ordered.append(name)

    for name in wanted:
        visit(name)
    return ordered


def _package_state(role: SystemRole) -> str:
    """One state per role.

    Mixed states within a role would need one task per package; the common case is a
    single state, and a mixed declaration falls back to ``present`` rather than silently
    dropping a removal.
    """
    states = {package.state for package in role.packages}
    return states.pop() if len(states) == 1 else "present"


def _asset_name(path: str) -> str:
    """Flat, collision-free file name for a role's ``files/`` directory."""
    return path.strip("/").replace("/", "_") or "file"
