#!/usr/bin/env bash
# Vendor a pinned copy of the external net2tf RAG into external/rag.
#
# The RAG lives in its own repository. This script copies a specific revision of it here
# so that builds are reproducible, and records what was copied. It never modifies the
# source checkout, and never copies legacy/ — that directory is the archived
# implementation and is explicitly unused by the active API.
set -euo pipefail

SOURCE="${1:-${TOPOFORGE_RAG_SOURCE:-$HOME/Projects/Advanced-RAG-For-Net_To_Cloud-Translation}}"
DESTINATION="${2:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/external/rag}"

if [[ ! -f "$SOURCE/app.py" ]]; then
  echo "error: $SOURCE does not look like the net2tf RAG (no app.py)" >&2
  echo "usage: $0 [source-checkout] [destination]" >&2
  exit 1
fi

revision="$(git -C "$SOURCE" rev-parse --short HEAD 2>/dev/null || echo unknown)"
echo "Vendoring the RAG from $SOURCE at revision $revision"

rm -rf "$DESTINATION"
mkdir -p "$DESTINATION"

# Only what the active API needs. legacy/, tests and caches are deliberately excluded.
for entry in app.py config.py planner.py retriever.py requirements.txt README.md kb docs tools; do
  if [[ -e "$SOURCE/$entry" ]]; then
    cp -r "$SOURCE/$entry" "$DESTINATION/"
  fi
done
find "$DESTINATION" -name '__pycache__' -type d -prune -exec rm -rf {} +

cat > "$DESTINATION/VENDORED.json" <<JSON
{
  "source": "$SOURCE",
  "revision": "$revision",
  "vendored_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "excluded": ["legacy/", "tests/", "index/", "generated/"],
  "note": "Generated by scripts/sync_external_rag.sh. Do not edit by hand."
}
JSON

echo "Vendored to $DESTINATION"
echo "Set TOPOFORGE_RAG__PATH=$DESTINATION and TOPOFORGE_RAG__BACKEND=legacy_net2tf to use it."
